### ISSUE TITLE
nil pointer dereference, validateHeader

### ISSUE THREAD

**Issue by timdrysdale** [practable/relay#49]
A nil pointer dereference occurred during develop branch testing
```
Jan 27 17:50:24 instance-1 session[164839]: 2023/01/27 17:50:24 http: panic serving 127.0.0.1:38336: runtime error: invalid memory address or nil pointer dereference
Jan 27 17:50:24 instance-1 session[164839]: goroutine 229 [running]:
Jan 27 17:50:24 instance-1 session[164839]: net/http.(*conn).serve.func1()
Jan 27 17:50:24 instance-1 session[164839]: #011/snap/go/10030/src/net/http/server.go:1850 +0xbf
Jan 27 17:50:24 instance-1 session[164839]: panic({0xa8b360, 0x1017730})
Jan 27 17:50:24 instance-1 session[164839]: #011/snap/go/10030/src/runtime/panic.go:890 +0x262
Jan 27 17:50:24 instance-1 session[164839]: github.com/practable/relay/internal/access.validateHeader.func1({0xc000030061, 0x1c})
Jan 27 17:50:24 instance-1 session[164839]: #011/var/lib/practable/sources/relay/internal/access/access.go:106 +0xd7
Jan 27 17:50:24 instance-1 session[164839]: github.com/go-openapi/runtime/security.APIKeyAuth.func3(0xc0001334a8?)
Jan 27 17:50:24 instance-1 session[164839]: #011/root/go/pkg/mod/github.com/go-openapi/runtime@v0.24.1/security/authenticator.go:178 +0x4b
Jan 27 17:50:24 instance-1 session[164839]: github.com/go-openapi/runtime/security.HttpAuthenticator.func1({0xa3f020?, 0xc000466100?})
Jan 27 17:50:24 instance-1 session[164839]: #011/root/go/pkg/mod/github.com/go-openapi/runtime@v0.24.1/security/authenticator.go:39 +0x55
Jan 27 17:50:24 instance-1 session[164839]: github.com/go-openapi/runtime.AuthenticatorFunc.Authenticate(0xa850a0?, {0xa3f020?, 0xc000466100?})
Jan 27 17:50:24 instance-1 session[164839]: #011/root/go/pkg/mod/github.com/go-openapi/runtime@v0.24.1/interfaces.go:73 +0x2c
Jan 27 17:50:24 instance-1 session[164839]: github.com/go-openapi/runtime/middleware.(*RouteAuthenticator).Authenticate(0xc000078d20, 0xc000138400, 0xc000138200)
Jan 27 17:50:24 instance-1 session[164839]: #011/root/go/pkg/mod/github.com/go-openapi/runtime@v0.24.1/middleware/router.go:186 +0x1ee
Jan 27 17:50:24 instance-1 session[164839]: github.com/go-openapi/runtime/middleware.RouteAuthenticators.Authenticate({0xc000092c60, 0x1, 0xff5ee8?}, 0x8?, 0xc000138200)
Jan 27 17:50:24 instance-1 session[164839]: #011/root/go/pkg/mod/github.com/go-openapi/runtime@v0.24.1/middleware/router.go:267 +0x1e8
Jan 27 17:50:24 instance-1 session[164839]: github.com/go-openapi/runtime/middleware.(*Context).Authorize(0xc000133718?, 0xc000138400, 0xc000138200)
Jan 27 17:50:24 instance-1 session[164839]: #011/root/go/pkg/mod/github.com/go-openapi/runtime@v0.24.1/middleware/context.go:429 +0xba
Jan 27 17:50:24 instance-1 session[164839]: github.com/practable/relay/internal/access/restapi/operations.(*Session).ServeHTTP(0xc000012510, {0xc50328, 0xc00048c000}, 0xc000138400)
Jan 27 17:50:24 instance-1 session[164839]: #011/var/lib/practable/sources/relay/internal/access/restapi/operations/session.go:53 +0xf2
Jan 27 17:50:24 instance-1 session[164839]: github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1({0xc50328, 0xc00048c000}, 0xc000138400)
Jan 27 17:50:24 instance-1 session[164839]: #011/root/go/pkg/mod/github.com/go-openapi/runtime@v0.24.1/middleware/operation.go:28 +0x59
Jan 27 17:50:24 instance-1 session[164839]: net/http.HandlerFunc.ServeHTTP(0x30?, {0xc50328?, 0xc00048c000?}, 0xc00005a7d8?)
Jan 27 17:50:24 instance-1 session[164839]: #011/snap/go/10030/src/net/http/server.go:2109 +0x2f
Jan 27 17:50:24 instance-1 session[164839]: github.com/go-openapi/runtime/middleware.NewRouter.func1({0xc50328, 0xc00048c000}, 0xc000138100)
Jan 27 17:50:24 instance-1 session[164839]: #011/root/go/pkg/mod/github.com/go-openapi/runtime@v0.24.1/middleware/router.go:78 +0x257
Jan 27 17:50:24 instance-1 session[164839]: net/http.HandlerFunc.ServeHTTP(0x3?, {0xc50328?, 0xc00048c000?}, 0xc00005a990?)
Jan 27 17:50:24 instance-1 session[164839]: #011/snap/go/10030/src/net/http/server.go:2109 +0x2f
Jan 27 17:50:24 instance-1 session[164839]: github.com/go-openapi/runtime/middleware.Redoc.func1({0xc50328, 0xc00048c000}, 0x7f42a0aa1ec0?)
Jan 27 17:50:24 instance-1 session[164839]: #011/root/go/pkg/mod/github.com/go-openapi/runtime@v0.24.1/middleware/redoc.go:72 +0x242
Jan 27 17:50:24 instance-1 session[164839]: net/http.HandlerFunc.ServeHTTP(0x0?, {0xc50328?, 0xc00048c000?}, 0x0?)
Jan 27 17:50:24 instance-1 session[164839]: #011/snap/go/10030/src/net/http/server.go:2109 +0x2f
Jan 27 17:50:24 instance-1 session[164839]: github.com/go-openapi/runtime/middleware.Spec.func1({0xc50328, 0xc00048c000}, 0x7f42a0a97d48?)
Jan 27 17:50:24 instance-1 session[164839]: #011/root/go/pkg/mod/github.com/go-openapi/runtime@v0.24.1/middleware/spec.go:46 +0x18c
Jan 27 17:50:24 instance-1 session[164839]: net/http.HandlerFunc.ServeHTTP(0x0?, {0xc50328?, 0xc00048c000?}, 0x46ab6e?)
Jan 27 17:50:24 instance-1 session[164839]: #011/snap/go/10030/src/net/http/server.go:2109 +0x2f
Jan 27 17:50:24 instance-1 session[164839]: net/http.serverHandler.ServeHTTP({0xc0005c2090?}, {0xc50328, 0xc00048c000}, 0xc000138100)
Jan 27 17:50:24 instance-1 session[164839]: #011/snap/go/10030/src/net/http/server.go:2947 +0x30c
Jan 27 17:50:24 instance-1 session[164839]: net/http.(*conn).serve(0xc00038c0a0, {0xc50a20, 0xc0000a41e0})
Jan 27 17:50:24 instance-1 session[164839]: #011/snap/go/10030/src/net/http/server.go:1991 +0x607
Jan 27 17:50:24 instance-1 session[164839]: created by net/http.(*Server).Serve
Jan 27 17:50:24 instance-1 session[164839]: #011/snap/go/10030/src/net/http/server.go:3102 +0x4db
Jan 27 18:17:01 instance-1 CRON[166020]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
```

Based on timing ... upgrading the token generation to include a booking_id field (that was empty) might be the culprit.

**Comment by timdrysdale** [comment]
There is a known issue causing a [panic when parsing with RegisteredClaims](https://pkg.go.dev/github.com/golang-jwt/jwt/v4#ParseWithClaims), but we are already following the advice to embedjwt.RegisteredClaims as a value not pointer. Testing with bad bearers did not recreate the problem. It's not clear how to recreate the issue. Since an issue occurred, we can protect against it stopping play in future should it occur again by adding panic recovery. Have added a [deferred panic recovery function](https://stackoverflow.com/questions/25638842/golang-recover-return-value-syntax) to the affected access.go/validateHeader(). Closing as "not repro" rather than "fixed", due to lack of test to repro issue/confirm fix.
